name: deploy_auth
on:
  push:
    branches:
      - b1
      - main
    paths: 
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ticket
    steps:
      - name: checkout repo
        uses: 'actions/checkout@v2'
      - name: test
        run: echo $DOCKER_PASSWORD &&echo DOCKER_USERNAME
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: login docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: build docker image 
        run: cd auth && docker build -t mars1836/ticketing-auth .
      - run: docker push mars1836/ticketing-auth
      
