name: tests-auth
on:
  pull_request:
    paths: 
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  
      - name: Install dependencies
        run: cd auth && npm install

      - name: Run tests
        run: cd auth && npm run test:ci
